# Generated by Django 4.2.23 on 2025-06-22 23:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('tipo_vivienda', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('finca', 'Finca')], default='casa', max_length=20)),
                ('tiene_experiencia_mascotas', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('administrador', 'Administrador')], default='usuario', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad_aproximada', models.IntegerField(help_text='en meses')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('tamaño', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=10)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='en kilogramos', max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('personalidad', models.TextField(blank=True)),
                ('necesidades_especiales', models.TextField(blank=True)),
                ('estado_salud', models.TextField()),
                ('vacunas_completas', models.BooleanField(default=False)),
                ('esterilizado', models.BooleanField(default=False)),
                ('microchip', models.BooleanField(default=False)),
                ('estado_adopcion', models.CharField(choices=[('disponible', 'Disponible'), ('en_proceso', 'En Proceso'), ('adoptado', 'Adoptado'), ('no_disponible', 'No Disponible')], default='disponible', max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_adopcion', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_admin_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_adopcion', models.TextField()),
                ('experiencia_previa', models.TextField(blank=True)),
                ('tiempo_disponible', models.TextField(blank=True)),
                ('otros_animales', models.TextField(blank=True)),
                ('situacion_vivienda', models.TextField(blank=True)),
                ('referencias_personales', models.TextField(blank=True)),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('comentarios_admin', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('id_admin_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='adopcion.mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'mascota', 'estado_solicitud')},
            },
        ),
        migrations.CreateModel(
            name='SeguimientoAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado_mascota', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('preocupante', 'Preocupante')], default='bueno', max_length=15)),
                ('recomendaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_admin_seguimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='adopcion.solicitudadopcion')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('no_leido', 'No Leído'), ('leido', 'Leído'), ('respondido', 'Respondido')], default='no_leido', max_length=10)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('id_admin_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_respondidos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto', models.ImageField(upload_to='mascotas_fotos/')),
                ('es_principal', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='adopcion.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_donante', models.CharField(max_length=100)),
                ('apellido_donante', models.CharField(max_length=100)),
                ('email_donante', models.EmailField(max_length=254)),
                ('telefono_donante', models.CharField(blank=True, max_length=20)),
                ('tipo_donacion', models.CharField(choices=[('monetaria', 'Monetaria'), ('insumos', 'Insumos')], max_length=10)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medio_pago', models.CharField(blank=True, choices=[('pce', 'PCE'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('cheque', 'Cheque')], max_length=10, null=True)),
                ('categoria_insumo', models.CharField(blank=True, choices=[('alimento_perro', 'Alimento para Perro'), ('alimento_gato', 'Alimento para Gato'), ('medicamentos', 'Medicamentos'), ('ropa', 'Ropa'), ('juguetes', 'Juguetes'), ('otros', 'Otros')], max_length=20, null=True)),
                ('descripcion_insumo', models.TextField(blank=True, help_text='Especifique el tipo y cantidad del insumo.')),
                ('fecha_donacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('comprobante_url', models.CharField(blank=True, max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='adopcion.mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'mascota')},
            },
        ),
    ]
