# Generated by Django 4.2.23 on 2025-06-23 19:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('tipo_vivienda', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('finca', 'Finca')], default='casa', max_length=20)),
                ('tiene_experiencia_mascotas', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('administrador', 'Administrador')], default='usuario', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad_aproximada', models.IntegerField(help_text='en meses', validators=[django.core.validators.MinValueValidator(0, message='La edad no puede ser negativa.'), django.core.validators.MaxValueValidator(204, message='La edad máxima es de 17 años (204 meses).')])),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('tamaño', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=10)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='en kilogramos', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='El peso debe ser mayor a 0.')])),
                ('color', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('personalidad', models.TextField(blank=True)),
                ('necesidades_especiales', models.TextField(blank=True)),
                ('estado_salud', models.TextField()),
                ('vacunas_completas', models.BooleanField(default=False)),
                ('esterilizado', models.BooleanField(default=False)),
                ('microchip', models.BooleanField(default=False)),
                ('estado_adopcion', models.CharField(choices=[('disponible', 'Disponible'), ('en_proceso', 'En Proceso'), ('adoptado', 'Adoptado'), ('no_disponible', 'No Disponible')], default='disponible', max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_adopcion', models.DateField(blank=True, null=True)),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal de la mascota', null=True, upload_to='mascotas/')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_admin_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vivienda', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('finca', 'Finca'), ('otro', 'Otro')], default='casa', max_length=30)),
                ('es_propia', models.BooleanField(default=False, verbose_name='¿La vivienda es propia?')),
                ('tiene_patio', models.BooleanField(default=False, verbose_name='¿Tiene patio o terraza?')),
                ('tamano_patio', models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=20)),
                ('adultos_en_casa', models.PositiveIntegerField(default=1, verbose_name='¿Cuántos adultos viven en la casa?')),
                ('ninos_en_casa', models.PositiveIntegerField(default=0, verbose_name='¿Cuántos niños viven en la casa?')),
                ('edades_ninos', models.TextField(blank=True, verbose_name='Edades de los niños')),
                ('tuvo_mascotas', models.BooleanField(default=False, verbose_name='¿Ha tenido mascotas antes?')),
                ('experiencia_mascotas', models.TextField(blank=True, verbose_name='Describa su experiencia con mascotas')),
                ('otras_mascotas', models.CharField(blank=True, max_length=100, verbose_name='¿Qué otras mascotas tiene actualmente?')),
                ('tiempo_diario', models.CharField(default='', max_length=50, verbose_name='¿Cuánto tiempo diario puede dedicarle a la mascota?')),
                ('todos_deacuerdo', models.BooleanField(default=False, verbose_name='¿Todos en casa están de acuerdo con la adopción?')),
                ('cuidador_principal', models.CharField(default='', max_length=100, verbose_name='¿Quién será el cuidador principal?')),
                ('plan_vacaciones', models.TextField(default='', verbose_name='¿Qué planes tiene para la mascota en vacaciones?')),
                ('ingreso_aproximado', models.CharField(default='', max_length=50, verbose_name='Ingreso mensual aproximado del hogar')),
                ('presupuesto_mensual_mascota', models.CharField(default='', max_length=50, verbose_name='Presupuesto mensual para la mascota')),
                ('tiene_veterinario', models.BooleanField(default=False, verbose_name='¿Tiene un veterinario de confianza?')),
                ('nombre_veterinario', models.CharField(blank=True, max_length=100)),
                ('motivo_adopcion', models.TextField(default='', verbose_name='¿Por qué desea adoptar?')),
                ('manejo_comportamiento', models.TextField(default='', verbose_name='¿Cómo manejaría un problema de comportamiento?')),
                ('compromiso_largo_plazo', models.BooleanField(default=False, verbose_name='¿Se compromete a cuidarlo por toda su vida? (15 años o más)')),
                ('acepta_visitas_seguimiento', models.BooleanField(default=False, verbose_name='¿Acepta visitas de seguimiento post-adopción?')),
                ('preferencias_mascota', models.TextField(blank=True, verbose_name='¿Tiene alguna preferencia sobre la mascota?')),
                ('comentario_extra', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('comentarios_admin', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('id_admin_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='adopcion.mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'mascota')},
            },
        ),
        migrations.CreateModel(
            name='SeguimientoAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado_mascota', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('preocupante', 'Preocupante')], default='bueno', max_length=15)),
                ('recomendaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_admin_seguimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='adopcion.solicitudadopcion')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('no_leido', 'No Leído'), ('leido', 'Leído'), ('respondido', 'Respondido')], default='no_leido', max_length=10)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('id_admin_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_respondidos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto', models.ImageField(upload_to='mascotas_fotos/')),
                ('es_principal', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='adopcion.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_donante', models.CharField(max_length=100)),
                ('apellido_donante', models.CharField(max_length=100)),
                ('email_donante', models.EmailField(max_length=254)),
                ('telefono_donante', models.CharField(blank=True, max_length=20)),
                ('tipo_donacion', models.CharField(choices=[('monetaria', 'Monetaria'), ('insumos', 'Insumos')], max_length=20)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='El monto debe ser mayor a 0.')])),
                ('medio_pago', models.CharField(blank=True, choices=[('pse', 'PSE'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('cheque', 'Cheque')], max_length=20, null=True)),
                ('categoria_insumo', models.CharField(blank=True, choices=[('alimentos', 'Alimentos'), ('medicamentos', 'Medicamentos'), ('juguetes', 'Juguetes'), ('arena', 'Arena para gatos'), ('otros', 'Otros')], max_length=20, null=True)),
                ('descripcion_insumo', models.TextField(blank=True, help_text='Describe los insumos que vas a donar.')),
                ('fecha_donacion', models.DateTimeField(auto_now_add=True)),
                ('comprobante_url', models.CharField(blank=True, max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='adopcion.mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'mascota')},
            },
        ),
    ]
