# Generated by Django 4.2.23 on 2025-06-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitudadopcion',
            unique_together={('usuario', 'mascota')},
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='acepta_visitas_seguimiento',
            field=models.BooleanField(default=False, verbose_name='¿Acepta visitas de seguimiento post-adopción?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='adultos_en_casa',
            field=models.PositiveIntegerField(default=1, verbose_name='¿Cuántos adultos viven en la casa?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='comentario_extra',
            field=models.TextField(blank=True, verbose_name='Comentarios adicionales'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='compromiso_largo_plazo',
            field=models.BooleanField(default=False, verbose_name='¿Se compromete a cuidarlo por toda su vida? (15 años o más)'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='cuidador_principal',
            field=models.CharField(default='', max_length=100, verbose_name='¿Quién será el cuidador principal?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='edades_ninos',
            field=models.TextField(blank=True, verbose_name='Edades de los niños'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='es_propia',
            field=models.BooleanField(default=False, verbose_name='¿La vivienda es propia?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='experiencia_mascotas',
            field=models.TextField(blank=True, verbose_name='Describa su experiencia con mascotas'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='ingreso_aproximado',
            field=models.CharField(default='', max_length=50, verbose_name='Ingreso mensual aproximado del hogar'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='manejo_comportamiento',
            field=models.TextField(default='', verbose_name='¿Cómo manejaría un problema de comportamiento?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='ninos_en_casa',
            field=models.PositiveIntegerField(default=0, verbose_name='¿Cuántos niños viven en la casa?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='nombre_veterinario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='otras_mascotas',
            field=models.CharField(blank=True, max_length=100, verbose_name='¿Qué otras mascotas tiene actualmente?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='plan_vacaciones',
            field=models.TextField(default='', verbose_name='¿Qué planes tiene para la mascota en vacaciones?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='preferencias_mascota',
            field=models.TextField(blank=True, verbose_name='¿Tiene alguna preferencia sobre la mascota?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='presupuesto_mensual_mascota',
            field=models.CharField(default='', max_length=50, verbose_name='Presupuesto mensual para la mascota'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='tamano_patio',
            field=models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='tiempo_diario',
            field=models.CharField(default='', max_length=50, verbose_name='¿Cuánto tiempo diario puede dedicarle a la mascota?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='tiene_patio',
            field=models.BooleanField(default=False, verbose_name='¿Tiene patio o terraza?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='tiene_veterinario',
            field=models.BooleanField(default=False, verbose_name='¿Tiene un veterinario de confianza?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='todos_deacuerdo',
            field=models.BooleanField(default=False, verbose_name='¿Todos en casa están de acuerdo con la adopción?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='tuvo_mascotas',
            field=models.BooleanField(default=False, verbose_name='¿Ha tenido mascotas antes?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='vivienda',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('finca', 'Finca'), ('otro', 'Otro')], default='casa', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='motivo_adopcion',
            field=models.TextField(default='', verbose_name='¿Por qué desea adoptar?'),
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='experiencia_previa',
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='otros_animales',
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='referencias_personales',
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='situacion_vivienda',
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='tiempo_disponible',
        ),
    ]
