# Generated by Django 4.2.23 on 2025-06-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_add_imagen_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='categoria_insumo',
            field=models.CharField(blank=True, choices=[('alimentos', 'Alimentos'), ('medicamentos', 'Medicamentos'), ('juguetes', 'Juguetes'), ('arena', 'Arena para gatos'), ('otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='descripcion_insumo',
            field=models.TextField(blank=True, help_text='Describe los insumos que vas a donar.'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha_donacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('pse', 'PSE'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='tipo_donacion',
            field=models.CharField(choices=[('monetaria', 'Monetaria'), ('insumos', 'Insumos')], max_length=20),
        ),
    ]
