# Generated by Django 4.2.23 on 2025-06-25 16:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_categoriadonacion_notificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='comprobante_url',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='edad_aproximada',
        ),
        migrations.AddField(
            model_name='donacion',
            name='admin_confirmador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donacion',
            name='anonimo',
            field=models.BooleanField(default=False, help_text='¿Deseas que tu donación sea anónima?'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='cantidad_insumo',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de unidades', null=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='ciudad_donante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donacion',
            name='comentarios_admin',
            field=models.TextField(blank=True, help_text='Comentarios internos del administrador'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='descripcion_especie',
            field=models.TextField(blank=True, help_text='Descripción de la donación en especie'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='descripcion_servicio',
            field=models.TextField(blank=True, help_text='Descripción del servicio'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='direccion_donante',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='estado_donacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='donacion',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='fecha_servicio',
            field=models.DateField(blank=True, help_text='Fecha para realizar el servicio', null=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='frecuencia',
            field=models.CharField(choices=[('unica', 'Donación Única'), ('mensual', 'Donación Mensual'), ('trimestral', 'Donación Trimestral'), ('semestral', 'Donación Semestral'), ('anual', 'Donación Anual')], default='unica', max_length=20),
        ),
        migrations.AddField(
            model_name='donacion',
            name='horas_servicio',
            field=models.PositiveIntegerField(blank=True, help_text='Horas de servicio', null=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='motivo_donacion',
            field=models.TextField(blank=True, help_text='¿Por qué decides donar?'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donacion',
            name='recibir_informacion',
            field=models.BooleanField(default=True, help_text='¿Deseas recibir información sobre el uso de tu donación?'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='tipo_identificacion',
            field=models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte'), ('nit', 'NIT'), ('otro', 'Otro')], default='cc', max_length=20),
        ),
        migrations.AddField(
            model_name='donacion',
            name='tipo_servicio',
            field=models.CharField(blank=True, help_text='Tipo de servicio ofrecido', max_length=100),
        ),
        migrations.AddField(
            model_name='donacion',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Ej: kg, litros, unidades', max_length=20),
        ),
        migrations.AddField(
            model_name='donacion',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad_aproximada_meses',
            field=models.IntegerField(blank=True, help_text='Edad aproximada en meses (se calcula automáticamente si no se proporciona fecha de nacimiento)', null=True, validators=[django.core.validators.MinValueValidator(0, message='La edad no puede ser negativa.'), django.core.validators.MaxValueValidator(204, message='La edad máxima es de 17 años (204 meses).')]),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento aproximada de la mascota', null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('pse', 'PSE'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='tipo_donacion',
            field=models.CharField(choices=[('monetaria', 'Monetaria'), ('insumos', 'Insumos'), ('servicios', 'Servicios'), ('especie', 'En Especie')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='categoria',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('joven', 'Joven'), ('adulto', 'Adulto'), ('senior', 'Senior'), ('especial', 'Necesidades Especiales'), ('urgente', 'Adopción Urgente'), ('rescatado', 'Recién Rescatado'), ('recuperacion', 'En Recuperación'), ('socializacion', 'En Socialización')], default='adulto', max_length=20),
        ),
    ]
