# Generated by Django 4.2.23 on 2025-06-23 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_alter_donacion_categoria_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='El monto debe ser mayor a 0.')]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad_aproximada',
            field=models.IntegerField(help_text='en meses', validators=[django.core.validators.MinValueValidator(0, message='La edad no puede ser negativa.'), django.core.validators.MaxValueValidator(204, message='La edad máxima es de 17 años (204 meses).')]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='en kilogramos', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='El peso debe ser mayor a 0.')]),
        ),
    ]
